dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    jarJar(implementation('org.jetbrains.kotlin:kotlin-stdlib:2.3.0'))
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.3.0")

    testImplementation("org.junit.jupiter:junit-jupiter:6.0.1")
    testImplementation("com.google.guava:guava:33.5.0-jre")
    testImplementation("it.unimi.dsi:fastutil:8.5.18")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    jarJar(api("net.ptcrys:RegistryLib:${registry_lib_version}"))

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "com.github.houbb:opencc4j:1.14.0"
    implementation "com.lowdragmc.ldlib2:ldlib2-neoforge-26.1:${ldlib2_version}"

    runtimeOnly("org.appliedenergistics:guideme:${guideme_version}")
    compileOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    runtimeOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"

    compileOnly "curse.maven:jade-324717:8068368"
    runtimeOnly "curse.maven:jade-324717:8068368"

    runtimeOnly "curse.maven:spark-361579:${spark_file_id}"
}
