# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.1.2
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1, 27)
# https://files.neoforged.neoforge.net/net/neoforged.neoforge/forge/
neo_version=26.1.2.71
neo_version_range=[26.1.0.71,)
loader_version_range=[4,)

## Mod Properties
mod_id=topo
mod_name=Topology
mod_license=Apache-2.0
mod_group_id=net.ptcrys
mod_authors=xinxinsuried,PhasetransCrystal
mod_description=
mod_url=https://github.com/PhasetransCrystal/Topology

jei_version=29.16.0.47
ldlib2_version=26.1.2.31
guideme_version=26.1.12-beta
ae2_version=26.1.10-beta
spark_file_id=7815877
registry_lib_version=26.7.27